# Generated by Django 5.1.6 on 2025-02-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_people', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('weekly_hours', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('authors', models.ManyToManyField(related_name='projects', to='api.author')),
            ],
        ),
    ]
