# Generated by Django 5.1.6 on 2025-02-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('weekly_hours', models.IntegerField()),
                ('no_of_people', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
