# Generated by Django 5.1.6 on 2025-02-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_image_url_project_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
    ]
