services:
  - type: web
    name: django-backend
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: "gunicorn backend.wsgi --bind 0.0.0.0:$PORT"