services:
  - type: web
    name: django-backend
    runtime: python
    plan: free
    buildCommand: |
      poetry install
      poetry run python manage.py migrate
      poetry run python manage.py collectstatic --noinput
    startCommand: "poetry run gunicorn backend.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString